-- Link -- https://leetcode.com/problems/top-travellers/description/
-- Question:
-- Write a solution to report the distance traveled by each user.
-- Return the result table ordered by travelled_distance in descending order, if two or more users traveled the same distance, 
-- order them by their name in ascending order.